model_name: feature_extractor+knn
net_name: resnet50
unfreezed_layers: 4
internal_features: 2048
net_size: [232, 232]
crop_size: [224, 224]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
warmup_epochs: 8
max_epochs: 80
base_lr: 0.001
margin: 2
class_per_batch: 4
elems_per_class: 32
examples_per_class: 10
n_neighbors: 5
merged_loss_coef: 0.5
synt_only: true