model_name: softmax_classifier
net_name: resnet50
unfreezed_layers: 3
internal_features: 1024
net_size: [232, 232]
crop_size: [224, 224]
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
smoothing_ratio: 0.1
warmup_epochs: 3
max_epochs: 30
base_lr: 0.001
batch_size: 512
